const data=
{
	"Akko": [
		{
			"Tên": "AKKO 5108 World Tour Tokyo R2 SP",
			"Model": "Full size",
			"Switch":"AKKO CS Switch",
			"Hotswap":"YES",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Dye-subbed",
			"Profile": "OSA",
			"Type": ["Lavender Purple", "Vintage White"],
			"Giá": "2,199,000 ₫",
			"Led": "RGB",
			"Kích thước": "442x132x41 mm",
			"Trọng lượng" :"1.2 kg"
		},
		{
			"Tên": "AKKO 3098B Multi-modes Prunus Lannesiana",
			"Model": "3098",
			"Switch":"AKKO CS Switch",
			"Hotswap":"YES",
			"Kết nối": ["USB Type C", "Bluetooth 5.0", "Wireless 2.4Ghz"],
			"Keycap": "PBT Double-Shot",
			"Profile": "ASA",
			"Type": ["Radiant Red", "Lavender Purple", "Vintage White"],
			"Giá": "2,099,000 ₫",
			"Led": "RGB",
			"Kích thước": "382x134x40 mm",
			"Trọng lượng" :"1.1 kg"
		},
		{
			"Tên": "AKKO 3098B Multi-modes World Tour Tokyo R2",
			"Model": "3098",
			"Switch":"AKKO CS Switch",
			"Hotswap":"YES",
			"Kết nối": ["USB Type C", "Bluetooth 5.0", "Wireless 2.4Ghz"],
			"Keycap": "PBT Dye-Subbed",
			"Profile": "OEM",
			"Type": ["Radiant Red", "Lavender Purple", "Vintage White"],
			"Giá": "2,299,000 ₫",
			"Led": "RGB",
			"Kích thước": "382x134x40 mm",
			"Trọng lượng" :"1.1 kg"
		},
		{
			"Tên": "AKKO 3098N Multi-modes Black Gold",
			"Model": "3098",
			"Switch":"TTC Switch",
			"Hotswap":"YES",
			"Kết nối": ["USB Type C", "Bluetooth 5.0", "Wireless 2.4Ghz"],
			"Keycap": "PBT Double-Shot",
			"Profile": "ASA",
			"Type": ["Gold Pink"],
			"Giá": "2,899,000 ₫",
			"Led": "RGB",
			"Kích thước": "382x134x40 mm",
			"Trọng lượng" :"1.1 kg"
		},
		{
			"Tên": "AKKO Designer Studio MOD001 – World Tour Tokyo",
			"Model": "3087",
			"Switch": "Cherry switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Dye-Subbed",
			"Profile": "OEM",
			"Type": ["Brown", "Red"],
			"Giá": "4,050,000 ₫",
			"Led": "",
			"Kích thước": "360x140x40 mm",
			"Trọng lượng" :"2 kg"
		},
		{
			"Tên": "AKKO Designer Studio MOD001 – Macaw",
			"Model": "3087",
			"Switch": "Cherry switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "OSA",
			"Type": ["Brown", "Red"],
			"Giá": "4,050,000 ₫",
			"Led": "",
			"Kích thước": "360x140x40 mm",
			"Trọng lượng" :"2 kg"
		},
		{
			"Tên": "AKKO Designer Studio MOD001 – Psittacus",
			"Model": "3087",
			"Switch": "Cherry switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "OSA",
			"Type": ["Brown", "Red"],
			"Giá": "4,050,000 ₫",
			"Led": "",
			"Kích thước": "360x140x40 mm",
			"Trọng lượng" :"2 kg"
		},
		{
			"Tên": "AKKO 3108 v2 DS Ocean Star",
			"Model": "Full size",
			"Switch":"AKKO switch v2",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "Cherry",
			"Type": ["Blue", "Orange", "Pink"],
			"Giá": "1,599,000 ₫",
			"Led": "",
			"Kích thước": "440x140x40 mm",
			"Trọng lượng" :"1.2 kg"
		},
		{
			"Tên": "AKKO 3098 DS Ocean Star",
			"Model": "3098",
			"Switch":"AKKO switch v2",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "Cherry",
			"Type": ["Blue", "Orange", "Pink"],
			"Giá": "1,599,000 ₫",
			"Led": "",
			"Kích thước": "382x134x40 mm",
			"Trọng lượng" :"0.97 kg"
		},
		{
			"Tên": "Mojike GK1 Black Red",
			"Model": "Full size",
			"Switch":"AKKO switch v2",
			"Hotswap":"NO",
			"Kết nối": [" USB, dây phím dính liền phím"],
			"Keycap": "PBT Double-Shot",
			"Profile": "OEM",
			"Type": ["Blue", "Orange", "Pink"],
			"Giá": "899,000 ₫",
			"Led": "Trắng",
			"Kích thước": "458x186x30 mm",
			"Trọng lượng" :"1 kg"
		},
		{
			"Tên": "Mojike GK1 Black Pink",
			"Model": "Full size",
			"Switch":"AKKO switch v2",
			"Hotswap":"NO",
			"Kết nối": ["USB, dây phím dính liền phím"],
			"Keycap": "PBT Double-Shot",
			"Profile": "OEM",
			"Type": ["Blue", "Orange", "Pink"],
			"Giá": "899,000 ₫",
			"Led": "Trắng",
			"Kích thước": "458x186x30 mm",
			"Trọng lượng" :"1 kg"
		},
		{
			"Tên": "AKKO 3098 v2 ASA – Los Angeles",
			"Model": "3098",
			"Switch":"AKKO CS Switch",
			"Hotswap":"YES",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "ASA",
			"Type": ["Ocean Blue", "Rose Red", "Matcha Green"],
			"Giá": "1,699,000 ₫",
			"Led": "",
			"Kích thước": "382x134x40 mm",
			"Trọng lượng" :"0.97 kg"
		},
		{
			"Tên": "AKKO 3084 v2 ASA – Los Angeles",
			"Model": "3084",
			"Switch":"AKKO CS Switch",
			"Hotswap":"YES",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "ASA",
			"Type": ["Ocean Blue", "Rose Red", "Matcha Green"],
			"Giá": "1,499,000 ₫",
			"Led": "",
			"Kích thước": "315x127x42 mm",
			"Trọng lượng" :"0.73 kg"
		},
		{
			"Tên": "AKKO 3098 v2 ASA – Black Pink",
			"Model": "3098",
			"Switch":"AKKO CS Switch",
			"Hotswap":"YES",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "ASA",
			"Type": ["Ocean Blue", "Rose Red", "Matcha Green"],
			"Giá": "1,699,000 ₫",
			"Led": "",
			"Kích thước": "382x134x40 mm",
			"Trọng lượng" :"0.97 kg"
		},
		{
			"Tên": "AKKO 3084 v2 ASA – Black Pink",
			"Model": "3084",
			"Switch":"AKKO CS Switch",
			"Hotswap":"YES",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "ASA",
			"Type": ["Ocean Blue", "Rose Red", "Matcha Green"],
			"Giá": "1,499,000 ₫",
			"Led": "",
			"Kích thước": "315x127x42 mm",
			"Trọng lượng" :"0.73 kg"
		},
		{
			"Tên": "AKKO 3108 DS Midnight R2",
			"Model": "Full size",
			"Switch":"AKKO switch v2",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "Cherry",
			"Type": ["Blue", "Orange", "Pink"],
			"Giá": "1,399,000 ₫",
			"Led": "",
			"Kích thước": "440x140x40 mm",
			"Trọng lượng" :"1.2 kg"
		},
		{
			"Tên": "AKKO 3098 DS Midnight R2",
			"Model": "3098",
			"Switch":"AKKO switch v2",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "Cherry",
			"Type": ["Blue", "Orange", "Pink"],
			"Giá": "1,399,000 ₫",
			"Led": "",
			"Kích thước": "382x134x40 mm",
			"Trọng lượng" :" 0.97 kg"
		},
		{
			"Tên": "AKKO 3108 Silent",
			"Model": "Full size",
			"Switch":"AKKO switch v2",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Dye-Subbed",
			"Profile": "OEM",
			"Type": ["Blue", "Orange", "Pink"],
			"Giá": "1,599,000 ₫",
			"Led": "",
			"Kích thước": "440x140x40 mm",
			"Trọng lượng" :"1.2 kg"
		},
		{
			"Tên": "AKKO 3087 Silent",
			"Model": "3087",
			"Switch": "Akko switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Dye-Subbed",
			"Profile": "OEM",
			"Type": ["Blue", "Orange", "Pink"],
			"Giá": "1,299,000 ₫",
			"Led": "",
			"Kích thước": "360x140x40 mm",
			"Trọng lượng" :"0.95 kg"
		},
		{
			"Tên": "AKKO 3084 Silent - Bluetooth 5.0",
			"Model": "3084",
			"Switch":"AKKO switch v2",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C", "Bluetooth 5.0"],
			"Keycap": "PBT Dye-Subbed",
			"Profile": "OEM",
			"Type": ["Blue", "Orange", "Pink"],
			"Giá": "1,599,000 ₫",
			"Led": "Trắng",
			"Kích thước": "315x127x42 mm",
			"Trọng lượng" :"0.73 kg"
		},
		{
			"Tên": "AKKO 5108 Honkai Impact 3rd – Cyberangel",
			"Model": "Full size",
			"Switch":"AKKO CS Jelly Switch",
			"Hotswap":"YES",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Dye-Subbed",
			"Profile": "JDA ",
			"Type": ["Jelly Pink", "Jelly Blue"],
			"Giá": "2,899,000 ₫",
			"Led": "RGB",
			"Kích thước": "442x132x41 mm",
			"Trọng lượng" :"1.2 kg"
		},
		{
			"Tên": "Akko 3108 v2 Honkai Impact 3rd – Yae Sakura",
			"Model": "Full size",
			"Switch":"AKKO switch v2",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Dye-Subbed",
			"Profile": "OEM",
			"Type": ["Blue", "Orange", "Pink"],
			"Giá": "2,099,000 ₫",
			"Led": "",
			"Kích thước": " 440x140x40 mm",
			"Trọng lượng" :"1.2 kg"
		},
		{
			"Tên": "Akko 3108 v2 Honkai Impact 3rd – Seele Vollerei",
			"Model": "Full size",
			"Switch": "AKKO switch v2",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Dye-Subbed",
			"Profile": "OEM",
			"Type": ["Blue", "Orange", "Pink"],
			"Giá": "1,599,000 ₫",
			"Led": "",
			"Kích thước": " 440x140x40 mm",
			"Trọng lượng" :"1.2 kg"
		},
		{
			"Tên": "AKKO 3068 v2 Year of the Ox",
			"Model": "3068",
			"Switch":"AKKO CS Switch",
			"Hotswap":"YES",
			"Kết nối": ["USB Type C", "Bluetooth 5.0"],
			"Keycap": "PBT Dye-Subbed",
			"Profile": "JDA",
			"Type": ["Ocean Blue", "Rose Red", "Matcha Green"],
			"Giá": "1,999,000 ₫",
			"Led": "RGB",
			"Kích thước": "312x102x40 mm",
			"Trọng lượng" :"0.59 kg"
		},
		{
			"Tên": "AKKO 3061S Neon RGB Bluetooth 5.0",
			"Model": "3061",
			"Switch": "Gateron switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C", "Bluetooth 5.0"],
			"Keycap": "PBT Double-Shot",
			"Profile": "Cherry",
			"Type": ["Pink", "Orange"],
			"Giá": "1,699,000 ₫",
			"Led": "RGB",
			"Kích thước": "292x101x370 mm",
			"Trọng lượng" :"0.5 kg"
		},
		{
			"Tên": "AKKO 3108 v2 Monet’s Pond",
			"Model": "Full size",
			"Switch": "AKKO switch v2",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Dye-Subbed",
			"Profile": "OEM",
			"Type": ["Blue", "Orange", "Pink"],
			"Giá": "1,799,000 ₫",
			"Led": "",
			"Kích thước": "440x140x40 mm",
			"Trọng lượng" :"1.2 kg"
		},
		{
			"Tên": "AKKO 3108 Dragon Ball Z – Frieza",
			"Model": "Full size",
			"Switch": "Akko switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Dye-Subbed",
			"Profile": "OEM",
			"Type": ["Blue", "Orange", "Pink"],
			"Giá": "1,799,000 ₫",
			"Led": "",
			"Kích thước": "440x140x40 mm",
			"Trọng lượng" :"1.2 kg"
		},
		{
			"Tên": "AKKO 3108 Dragon Ball Z – Vegeta",
			"Model": "Full size",
			"Switch":"Akko switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Dye-Subbed",
			"Profile": "OEM",
			"Type": ["Blue", "Orange", "Pink"],
			"Giá": "1,699,000 ₫",
			"Led": "",
			"Kích thước": "440x140x40 mm",
			"Trọng lượng" :"1.2 kg"
		},
		{
			"Tên": "AKKO 3108 v2 DS Horizon",
			"Model": "Full size",
			"Switch":"AKKO switch v2",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Dye-Subbed",
			"Profile": "Cherry",
			"Type": ["Blue", "Orange", "Pink"],
			"Giá": "1,599,000 ₫",
			"Led": "",
			"Kích thước": "440x140x40 mm",
			"Trọng lượng" :"1.2 kg"
		},
		{
			"Tên": "AKKO 3087 v2 DS Horizon",
			"Model": "3087",
			"Switch":"AKKO switch v2",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Dye-Subbed",
			"Profile": "Cherry",
			"Type": ["Blue", "Orange", "Pink"],
			"Giá": "1,399,000 ₫",
			"Led": "",
			"Kích thước": "360x140x40 mm",
			"Trọng lượng" :"0.95 kg"
		},
		{
			"Tên": "AKKO 3108 v2 OSA – Macaw",
			"Model": "Full size",
			"Switch": "Gateron switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "OSA",
			"Type": ["Gateron Yellow"],
			"Giá": "1,950,000 ₫",
			"Led": "",
			"Kích thước": "440x140x40 mm",
			"Trọng lượng" :"1.2 kg"
		},
		{
			"Tên": "AKKO 3108 v2 Steam Engine",
			"Model": "Full size",
			"Switch": "AKKO switch v2",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Dye-Subbed",
			"Profile": "OEM",
			"Type": ["Blue", "Orange", "Pink"],
			"Giá": "1,599,000 ₫",
			"Led": "",
			"Kích thước": "440x140x40 mm",
			"Trọng lượng" :"1.2 kg"
		},
		{
			"Tên": "AKKO 3108 v2 DS Matcha Red Bean",
			"Model": "Full size",
			"Switch": "AKKO switch v2",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Dye-Subbed",
			"Profile": "OEM",
			"Type": ["Blue", "Orange", "Pink"],
			"Giá": "1,399,000 ₫",
			"Led": "",
			"Kích thước": "360x140x40 mm",
			"Trọng lượng" :"0.95 kg"
		},
		{
			"Tên": "AKKO 3098 v2 DS Matcha Red Bean",
			"Model": "3098",
			"Switch": "AKKO switch v2",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "Cherry",
			"Type": ["Blue", "Orange", "Pink"],
			"Giá": "1,599,000 ₫",
			"Led": "",
			"Kích thước": "382x134x40 mm",
			"Trọng lượng" :"0.97 kg"
		},
		{
			"Tên": "AKKO 3108 v2 One Piece – Luffy",
			"Model": "Full size",
			"Switch": "AKKO switch v2",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Dye-Subbed",
			"Profile": "OEM",
			"Type": ["Blue", "Orange", "Pink"],
			"Giá": "1,699,000 ₫",
			"Led": "",
			"Kích thước": "440x140x40 mm",
			"Trọng lượng" :"1.2 kg"
		},
		{
			"Tên": "AKKO 3087 v2 One Piece – Luffy",
			"Model": "3087",
			"Switch": "AKKO switch v2",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Dye-Subbed",
			"Profile": "OEM",
			"Type": ["Blue", "Orange", "Pink"],
			"Giá": "1,499,000 ₫",
			"Led": "",
			"Kích thước": "360x140x40 mm",
			"Trọng lượng" :"0.95 kg"
		},
		{
			"Tên": "Akko 3087 v2 One Piece – Chopper",
			"Model": "3087",
			"Switch": "AKKO switch v2",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Dye-Subbed",
			"Profile": "OEM",
			"Type": ["Blue", "Orange", "Pink"],
			"Giá": "1,499,000 ₫",
			"Led": "",
			"Kích thước": "360x140x40 mm",
			"Trọng lượng" :"0.95 kg"
		},
		{
			"Tên": "AKKO 3108 v2 Bilibili",
			"Model": "Full size",
			"Switch":"Akko switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Dye-Subbed",
			"Profile": "OEM",
			"Type": ["Blue", "Orange", "Pink"],
			"Giá": "1,699,000 ₫",
			"Led": "",
			"Kích thước": "440x140x40 mm",
			"Trọng lượng" :"1.2 kg"
		},
		{
			"Tên": "AKKO 3087 v2 Bilibili",
			"Model": "3087",
			"Switch":"Akko switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Dye-Subbed",
			"Profile": "OEM",
			"Type": ["Blue", "Orange", "Pink"],
			"Giá": "1,499,000 ₫",
			"Led": "",
			"Kích thước": "360x140x40 mm",
			"Trọng lượng" :"0.95 kg"
		}	
	],
	"Leopold" :[
		{
			"Tên": "Leopold FC980M PD White Blue Star",
			"Model": "3098",
			"Switch": "Cherry MX Switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "Cherry",
			"Type": ["Blue", "Brown", "Red", "Silent Red"],
			"Giá": "3,770,000 ₫",
			"Led": "",
			"Kích thước": "325x109x33 mm",
			"Trọng lượng" :"0.7 kg"
		},
		{
			"Tên": "Leopold FC900R PD White Blue Star",
			"Model": "Full size",
			"Switch": "Cherry MX Switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "Cherry",
			"Type": ["Blue", "Brown", "Red", "Silent Red"],
			"Giá": "3,470,000 ₫",
			"Led": "",
			"Kích thước": "440x140x33 mm",
			"Trọng lượng" :"1.2 kg"
		},
		{
			"Tên": "Leopold FC750R PD White Blue Star",
			"Model": "3087",
			"Switch": "Cherry MX Switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "Cherry",
			"Type": ["Blue", "Brown", "Red", "Silent Red"],
			"Giá": "3,270,000 ₫",
			"Led": "",
			"Kích thước": "360x140x40 mm",
			"Trọng lượng" :"0.95 kg"
		},
		{
			"Tên": "Leopold FC660M PD White Blue Star",
			"Model": "3066",
			"Switch": "Cherry MX Switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "Cherry",
			"Type": ["Blue", "Brown", "Red", "Silent Red"],
			"Giá": "2,750,000 ₫",
			"Led": "",
			"Kích thước": "325x109x24 mm",
			"Trọng lượng" :"0.7 kg"
		},
		{
			"Tên": "Leopold FC660MPD Blue Grey",
			"Model": "3066",
			"Switch": "Cherry MX Switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "Cherry",
			"Type": ["Blue", "Brown", "Red", "Silent Red"],
			"Giá": "2,750,000 ₫",
			"Led": "",
			"Kích thước": "325x109x24 mm",
			"Trọng lượng" :"0.7 kg"
		},
		{
			"Tên": "Leopold FC650MDS Blue Grey",
			"Model": "3065",
			"Switch": "Cherry MX Switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "Cherry",
			"Type": ["Blue", "Brown", "Red", "Silent Red"],
			"Giá": "2,970,000 ₫",
			"Led": "",
			"Kích thước": "325x109x24 mm",
			"Trọng lượng" :"0.7 kg"
		},
		{
			"Tên": "Leopold FC980M OE White Mint",
			"Model": "3098",
			"Switch": "Cherry MX Switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "Cherry",
			"Type": ["Blue", "Brown", "Red", "Silent Red"],
			"Giá": "3,689,000 ₫",
			"Led": "",
			"Kích thước": "325x109x33 mm",
			"Trọng lượng" :"0.7 kg"
		},
		{
			"Tên": "Leopold FC750R PD WhiteMint",
			"Model": "3087",
			"Switch": "Cherry MX Switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "Cherry",
			"Type": ["Blue", "Brown", "Red"],
			"Giá": "3,270,000 ₫",
			"Led": "",
			"Kích thước": "362x140x33 mm",
			"Trọng lượng" :"0.95 kg"
		},
		{
			"Tên": "Leopold FC900R PD Grey Purple",
			"Model": "Full size",
			"Switch": "Cherry MX Switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "Cherry",
			"Type": ["Brown", "Red", "Silent Red"],
			"Giá": "3,270,000 ₫",
			"Led": "",
			"Kích thước": "440x140x33 mm",
			"Trọng lượng" :"1.2 kg"
		},
		{
			"Tên": "Leopold FC750R PD Grey Purple",
			"Model": "3087",
			"Switch": "Cherry MX Switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "Cherry",
			"Type": ["Brown", "Red", "Silent Red"],
			"Giá": "3,150,000 ₫",
			"Led": "",
			"Kích thước": "362x140x33 mm",
			"Trọng lượng" :"1 kg"
		},
		{
			"Tên": "Leopold FC750R PD White Dark Grey",
			"Model": "3087",
			"Switch": "Cherry MX Switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "Cherry",
			"Type": ["Brown", "Red", "Silent Red"],
			"Giá": "3.270.000 ₫",
			"Led": "",
			"Kích thước": "362x140x33 mm",
			"Trọng lượng" :"1 kg"
		},
		{
			"Tên": "Leopold FC660M PD White Dark Grey",
			"Model": "3066",
			"Switch": "Cherry MX Switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "Cherry",
			"Type": ["Blue", "Brown", "Red", "Silent Red"],
			"Giá": "2.750.000 ₫",
			"Led": "",
			"Kích thước": "325x109x24 mm",
			"Trọng lượng" :"0.7 kg"
		},
		{
			"Tên": "Leopold FC980M PD White Grey",
			"Model": "3098",
			"Switch": "Cherry MX Switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "Cherry",
			"Type": ["Blue", "Brown", "Silent Red"],
			"Giá": "3,770,000 ₫",
			"Led": "",
			"Kích thước": "325x109x33 mm",
			"Trọng lượng" :"0.7 kg"
		},
		{
			"Tên": "Leopold FC900R PD White Grey",
			"Model": "Full size",
			"Switch": "Cherry MX Switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "Cherry",
			"Type": ["Blue", "Brown","Red", "Silent Red"],
			"Giá": "3,770,000 ₫",
			"Led": "",
			"Kích thước": "440x140x33 mm",
			"Trọng lượng" :"1.2 kg"
		},
		{
			"Tên" :"Leopold FC900R PD Sweden - White Case",
			"Model": "Full size",
			"Switch": "Cherry MX Switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "Cherry",
			"Type": ["Blue", "Brown","Red", "Silent Red"],
			"Giá": "3,449,000 ₫",
			"Led": "",
			"Kích thước": "440x140x33 mm",
			"Trọng lượng" :"1.2 kg"
		},
		{
			"Tên" :"Leopold FC750R PD Sweden - White Case",
			"Model": "3087",
			"Switch": "Cherry MX Switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "Cherry",
			"Type": ["Blue", "Brown", "Red", "Silent Red"],
			"Giá": "3,270,000 ₫",
			"Led": "",
			"Kích thước": "360x140x40 mm",
			"Trọng lượng" :"0.95 kg"
		},
		{
			"Tên": "Leopold FC660M PD Sweden - White Case",
			"Model": "3066",
			"Switch": "Cherry MX Switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "Cherry",
			"Type": ["Blue", "Brown", "Red", "Silent Red"],
			"Giá": "2,750,000 ₫",
			"Led": "",
			"Kích thước": "325x109x24 mm",
			"Trọng lượng" :"0.7 kg"
		},
		{
			"Tên": "Leopold FC900R PD OEM Sweden",
			"Model": "Full size",
			"Switch": "Cherry MX Switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "OEM",
			"Type": ["Blue", "Brown","Red", "Silent Red"],
			"Giá": "3,449,000 ₫",
			"Led": "",
			"Kích thước": "440x140x33 mm",
			"Trọng lượng" :"1.2 kg"
		},
		{
			"Tên": "Leopold FC750R PD OEM Sweden",
			"Model": "3087",
			"Switch": "Cherry MX Switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "OEM",
			"Type": ["Blue", "Brown", "Red", "Silent Red"],
			"Giá": "3,270,000 ₫",
			"Led": "",
			"Kích thước": "360x140x40 mm",
			"Trọng lượng" :"0.95 kg"
		},
		{
			"Tên": "Leopold FC900R BlueBlack PS",
			"Model": "Full size",
			"Switch": "Cherry MX Switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap":"PBT Dye-Subbed",
			"Profile": "Cherry",
			"Type": ["Blue", "Brown","Red", "Silent Red"],
			"Giá": "3,470,000 ₫",
			"Led": "",
			"Kích thước": "440x140x33 mm",
			"Trọng lượng" :"1.2 kg"
		},
		{
			"Tên": "Leopold FC750R PS BlueBlack",
			"Model": "3087",
			"Switch": "Cherry MX Switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C"],
			"Keycap": "PBT Double-Shot",
			"Profile": "OEM",
			"Type": ["Blue", "Brown", "Red", "Silent Red"],
			"Giá": "3,049,000 ₫",
			"Led": "",
			"Kích thước": "360x140x40 mm",
			"Trọng lượng" :"0.95 kg"
		}
	],
	"Keychron":[
		{
			"Tên": "Keychron K1v4",
			"Model": "3087",
			"Switch":"Gateron switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C", "Bluetooth 5.1"],
			"Keycap": "ABS",
			"Profile": "Low profile",
			"Type": ["Blue", "Brown", "Red"],
			"Giá": "2,190,000 ₫",
			"Led": "RGB",
			"Kích thước": "355x120x18 mm",
			"Trọng lượng" :"0.65 kg"
		},
		{
			"Tên": "Keychron K2v2",
			"Model": "3084",
			"Switch": "Gateron switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C", "Bluetooth 5.1"],
			"Keycap": "ABS",
			"Profile": "Low profile",
			"Type": ["Blue", "Brown", "Red"],
			"Giá": "1,690,000 ₫",
			"Led": "RGB",
			"Kích thước": "313x123x18 mm",
			"Trọng lượng" :"0.65 kg"
		},
		{
			"Tên": "Keychron K3v2",
			"Model": "3084",
			"Switch": "Gateron switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C", "Bluetooth 5.1"],
			"Keycap": "ABS",
			"Profile": "Low profile",
			"Type": ["Blue", "Brown", "Red"],
			"Giá": "2,190,000 ₫",
			"Led": "RGB",
			"Kích thước": "306x116x22 mm",
			"Trọng lượng" :"0.395 kg"
		},
		{
			"Tên": "Keychron K4v2",
			"Model": "3100",
			"Switch": "Gateron switch",
			"Hotswap":"NO",
			"Kết nối": ["USB Type C", "Bluetooth 5.1"],
			"Keycap": "ABS",
			"Profile": "Low profile",
			"Type": ["Blue", "Brown", "Red"],
			"Giá": "1,850,000 ₫",
			"Led": "RGB",
			"Kích thước": "371x124x38 mm",
			"Trọng lượng" :"0.77 kg"
		},
		{
			"Tên": "Keychron K6",
			"Model": "3068",
			"Switch": "Gateron switch",
			"Hotswap":"YES",
			"Kết nối": ["USB Type C", "Bluetooth 5.1"],
			"Keycap": "ABS",
			"Profile": "Low profile",
			"Type": ["Blue", "Brown", "Red"],
			"Giá": "1,690,000 ₫",
			"Led": "RGB",
			"Kích thước": "313x104x38 mm",
			"Trọng lượng" :"0.53 kg"
		},
		{
			"Tên": "Keychron K8",
			"Model": "3087",
			"Switch": "Gateron switch",
			"Hotswap":"YES",
			"Kết nối": ["USB Type C", "Bluetooth 5.1"],
			"Keycap": "ABS",
			"Profile": "Low profile",
			"Type": ["Blue", "Brown", "Red"],
			"Giá": "1,790,000 ₫",
			"Led": "RGB",
			"Kích thước": "355x123x38 mm",
			"Trọng lượng" :"0.74 kg"
		}
	]
}